apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "govd.fullname" . }}
  labels:
    {{- include "govd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "govd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "govd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "govd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: profiler
              containerPort: 6060
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "govd.fullname" . }}-secret
            - configMapRef:
                name: {{ include "govd.fullname" . }}-config
          volumeMounts:
            - name: downloads
              mountPath: /app/downloads
            - name: logs
              mountPath: /app/logs
            - name: private
              mountPath: /app/private
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: downloads
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "govd.fullname" . }}-downloads
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: logs
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "govd.fullname" . }}-logs
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: private
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "govd.fullname" . }}-private
          {{- else }}
          emptyDir: {}
          {{- end }}
