apiVersion: v1
kind: Secret
metadata:
  name: {{ include "govd.fullname" . }}-secret
  labels:
    {{- include "govd.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOT_TOKEN: {{ .Values.bot.token | quote }}
  {{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.password | quote }}
  {{- else }}
  DB_PASSWORD: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
