apiVersion: v1
kind: Service
metadata:
  name: {{ include "govd.fullname" . }}
  labels:
    {{- include "govd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.profilerPort }}
      targetPort: profiler
      protocol: TCP
      name: profiler
  selector:
    {{- include "govd.selectorLabels" . | nindent 4 }}
